### ISSUE TITLE
Issue with Omega

### ISSUE THREAD

**Issue by TildeEthDoUsPart** [hallowed/calcboy#1]
I've been trying to compile omega with calcboy on my Numworks, but I keep encountering the same issue:
```
~/Omega $ make GB_ROM='/home/ethan/Downloads/properroms/prism-v0.94-b0237.gbc' epsilon_flash
Building O1.20.3-E14.4.1
  Targetting Numworks 
    Building on Linux amd64

ICON    apps/calcboy/calcboy_icon.png
Traceback (most recent call last):
  File "themes/themes_manager.py", line 203, in <module>
    main(args)
  File "themes/themes_manager.py", line 181, in main
    handle_theme(args, os.path.dirname(os.path.realpath(__file__)) + os.path.sep + "themes" + os.path.sep + "local")
  File "themes/themes_manager.py", line 150, in handle_theme
    icon_path = path + os.path.sep + data["icons"] + os.path.sep + icons[args.output.replace(args.build_dir, "")]
KeyError: 'apps/calcboy/calcboy_icon.png'
make: *** [apps/Makefile:98: output/release/device/n0110/apps/calcboy/calcboy_icon.png] Error 1
```
I'm on Debian 10. I can't see what goes wrong, any ideas?

**Comment by lennardwalter** [comment]
You can just add this line: `"apps/calcboy/calcboy_icon.png" : "apps/calcboy_icon.png",` to `Omega/themes/icons.json`. Should work but I will also think about a more general solution and push it into the repo:)

**Comment by TildeEthDoUsPart** [comment]
Ah, thanks for the reply. It works correctly now.
